import type { GraphNode, GraphProject, NodeKind, ToolConfig } from '../../core/graph/types';
import type { ValidationResult } from '../../core/validation/types';
import type { AdkAdapterAnalysis, AdkAdapterSettings } from './types';
import type { AdkCodeGeneration, AdkGeneratedFile } from './codegenTypes';

const kindPrefix: Record<NodeKind, string> = {
  agent: 'agent',
  router: 'router',
  tool: 'tool',
  humanInput: 'human_input',
  join: 'join',
};

const pyString = (value: string) => JSON.stringify(value) ?? '""';
const oneLine = (value: string) => value.replace(/\s+/g, ' ').trim();

const toolConfigLines = (config: ToolConfig): string[] => {
  switch (config.toolType) {
    case 'custom':
      return [
        `type=custom`,
        `functionName=${config.functionName || '(unset)'}`,
        `description=${oneLine(config.description) || '(unset)'}`,
      ];
    case 'http':
      return [`type=http`, `method=${config.method}`, `url=${config.url || '(unset)'}`];
    case 'mcp':
      return config.transport === 'stdio'
        ? [
            `type=mcp`,
            `transport=stdio`,
            `command=${config.command || '(unset)'}`,
            `args=${config.args || '(none)'}`,
          ]
        : [`type=mcp`, `transport=sse`, `url=${config.url || '(unset)'}`];
    case 'search':
      return [`type=search`, `provider=${config.provider || '(unset)'}`];
    case 'database':
      return [
        `type=database`,
        `connectionRef=${config.connectionRef || '(unset)'}`,
        `operation=${config.operation || '(unset)'}`,
      ];
    case 'file':
      return [`type=file`, `operation=${config.operation}`, `path=${config.path || '(unset)'}`];
  }
};

const makeSymbolMap = (project: GraphProject) => {
  const symbols = new Map<string, string>();
  project.nodes.forEach((node, index) => {
    symbols.set(node.id, `${kindPrefix[node.kind]}_${String(index + 1).padStart(2, '0')}`);
  });
  return symbols;
};

const generateAgentPy = (
  project: GraphProject,
  settings: AdkAdapterSettings,
  symbols: Map<string, string>,
) => {
  const hasAgent = project.nodes.some((node) => node.kind === 'agent');
  const hasRouter = project.nodes.some((node) => node.kind === 'router');
  const hasHumanInput = project.nodes.some((node) => node.kind === 'humanInput');
  const hasJoin = project.nodes.some((node) => node.kind === 'join');

  const imports = ['from google.adk import Workflow'];
  if (hasAgent) imports[0] = 'from google.adk import Agent, Workflow';
  if (hasRouter) {
    imports[0] = hasAgent
      ? 'from google.adk import Agent, Event, Workflow'
      : 'from google.adk import Event, Workflow';
  }
  if (hasHumanInput) imports.push('from google.adk.events.request_input import RequestInput');
  if (hasHumanInput || hasJoin) {
    const names = [hasJoin ? 'JoinNode' : '', hasHumanInput ? 'node' : ''].filter(Boolean);
    imports.push(`from google.adk.workflow import ${names.join(', ')}`);
  }

  const lines: string[] = [
    '"""Generated by Agent Graph Designer.',
    '',
    `Canvas project: ${oneLine(project.name)}`,
    'Target: Google ADK 2.x Graph Workflow',
    '',
    'TODO markers are intentional. The generator does not invent missing business logic.',
    '"""',
    '',
    ...imports,
    '',
    `ADK_DEFAULT_MODEL = ${pyString(settings.defaultModel)}`,
    '',
  ];

  const todos: string[] = [];

  for (const node of project.nodes) {
    const symbol = symbols.get(node.id) ?? node.id;
    switch (node.kind) {
      case 'agent':
        lines.push(
          `${symbol} = Agent(`,
          `    name=${pyString(symbol)},`,
          `    model=ADK_DEFAULT_MODEL,`,
          `    description=${pyString(`${node.name}: ${node.description}`)},`,
          `    instruction=${pyString(node.config.instruction)},`,
          ')',
          '',
        );
        break;

      case 'router': {
        const routeKeys = project.edges
          .filter((edge) => edge.sourceNodeId === node.id)
          .map((edge) => edge.routeKey?.trim() ?? '')
          .filter(Boolean);
        const routeHint = routeKeys.length > 0 ? routeKeys.join(' / ') : '(none)';
        lines.push(
          `def ${symbol}(node_input):`,
          `    """Canvas Router: ${oneLine(node.name)}"""`,
          `    # Canvas condition: ${oneLine(node.config.condition) || '(unset)'}`,
          `    # Allowed route keys: ${routeHint}`,
          `    # TODO: Convert the Canvas condition into executable Python logic.`,
          `    # Example shape: return Event(output=node_input, route=${pyString(routeKeys[0] ?? 'ROUTE_KEY')})`,
          `    raise NotImplementedError(${pyString(`TODO: implement Router logic for ${node.name}`)})`,
          '',
        );
        todos.push(`${node.name}: Router condition is design text and must be implemented as executable logic.`);
        break;
      }

      case 'tool':
        lines.push(
          `def ${symbol}(node_input):`,
          `    """Canvas Tool: ${oneLine(node.name)}"""`,
          ...toolConfigLines(node.config).map((line) => `    # ${line}`),
        );
        if (node.config.toolType === 'mcp') {
          lines.push(
            '    # NOTE: McpToolset is supported on LLM agents, but a public deterministic',
            '    # ToolsetNode for Graph Workflow is not generated here.',
            '    # TODO: Choose either an LLM Agent + McpToolset design or a supported',
            '    # deterministic wrapper when the runtime semantics are defined.',
          );
          todos.push(`${node.name}: choose how the MCP tool is invoked inside the workflow.`);
        } else {
          lines.push(
            '    # TODO: Implement this Tool wrapper. Do not hard-code credentials or secrets.',
          );
          todos.push(`${node.name}: implement ${node.config.toolType} Tool runtime logic.`);
        }
        lines.push(
          `    raise NotImplementedError(${pyString(`TODO: implement Tool node ${node.name}`)})`,
          '',
        );
        break;

      case 'humanInput':
        lines.push(
          '@node(rerun_on_resume=False)',
          `async def ${symbol}(node_input):`,
          `    yield RequestInput(`,
          `        message=${pyString(node.config.prompt)},`,
          '        response_schema=str,',
          '    )',
          '',
        );
        break;

      case 'join':
        lines.push(`${symbol} = JoinNode(name=${pyString(symbol)})`, '');
        break;
    }
  }

  const validEdges = project.edges.filter(
    (edge) => symbols.has(edge.sourceNodeId) && symbols.has(edge.targetNodeId),
  );
  const incomingCounts = new Map(project.nodes.map((node) => [node.id, 0]));
  validEdges.forEach((edge) => {
    incomingCounts.set(edge.targetNodeId, (incomingCounts.get(edge.targetNodeId) ?? 0) + 1);
  });
  const entryNodes = project.nodes.filter((node) => (incomingCounts.get(node.id) ?? 0) === 0);
  const nodeById = new Map(project.nodes.map((node) => [node.id, node]));

  lines.push('edges = [');
  if (entryNodes.length === 1) {
    lines.push(`    ("START", ${symbols.get(entryNodes[0].id)}),`);
  } else if (entryNodes.length > 1) {
    lines.push(
      `    ("START", (${entryNodes.map((node) => symbols.get(node.id)).join(', ')})),`,
    );
  } else {
    lines.push('    # TODO: No entry node was found. Check cycles and incoming edges.');
    todos.push('Workflow has no entry node connected from START.');
  }

  const routerIds = new Set(project.nodes.filter((node) => node.kind === 'router').map((node) => node.id));
  const routerEdges = new Map<string, typeof validEdges>();

  for (const edge of validEdges) {
    if (routerIds.has(edge.sourceNodeId)) {
      const list = routerEdges.get(edge.sourceNodeId) ?? [];
      list.push(edge);
      routerEdges.set(edge.sourceNodeId, list);
      continue;
    }
    lines.push(
      `    (${symbols.get(edge.sourceNodeId)}, ${symbols.get(edge.targetNodeId)}),`,
    );
  }

  for (const [routerId, edges] of routerEdges) {
    const routerSymbol = symbols.get(routerId);
    const usedKeys = new Set<string>();
    const mappings: string[] = [];

    for (const edge of edges) {
      const key = edge.routeKey?.trim() ?? '';
      if (!key) {
        const targetName = nodeById.get(edge.targetNodeId)?.name ?? edge.targetNodeId;
        todos.push(`${nodeById.get(routerId)?.name ?? routerId} → ${targetName}: routeKey is missing.`);
        continue;
      }
      if (usedKeys.has(key)) {
        todos.push(`${nodeById.get(routerId)?.name ?? routerId}: duplicate routeKey ${key}.`);
        continue;
      }
      usedKeys.add(key);
      mappings.push(`${pyString(key)}: ${symbols.get(edge.targetNodeId)}`);
    }

    if (mappings.length > 0) {
      lines.push(`    (${routerSymbol}, {${mappings.join(', ')}}),`);
    } else {
      lines.push(`    # TODO: ${routerSymbol} has no usable route mapping.`);
    }
  }

  lines.push(']', '', 'root_agent = Workflow(name="root_agent", edges=edges)', '');

  if (project.nodes.length === 0) {
    todos.push('Canvas has no nodes.');
  }

  return { content: lines.join('\n'), todos };
};

const generateMappingReport = (
  project: GraphProject,
  settings: AdkAdapterSettings,
  symbols: Map<string, string>,
  validation: ValidationResult,
  analysis: AdkAdapterAnalysis,
  todos: string[],
) => {
  const lines = [
    '# ADK Code Generation Mapping',
    '',
    `- Project: ${project.name}`,
    '- Target: Google ADK 2.x Graph Workflow / Python',
    `- Default model: ${settings.defaultModel || '(unset)'}`,
    `- Validation errors: ${validation.errors.length}`,
    `- Validation warnings: ${validation.warnings.length}`,
    `- Adapter blockers: ${analysis.blockedCount}`,
    `- Generator TODOs: ${todos.length}`,
    '',
    '## Node → Python symbol',
  ];

  if (project.nodes.length === 0) {
    lines.push('- No nodes');
  } else {
    project.nodes.forEach((node) => {
      lines.push(`- ${node.name} (${node.kind}) → \`${symbols.get(node.id)}\``);
    });
  }

  lines.push('', '## Generator TODOs');
  if (todos.length === 0) lines.push('- None');
  else todos.forEach((todo) => lines.push(`- ${todo}`));

  lines.push('', '## Validation');
  if (validation.issues.length === 0) lines.push('- No Error / Warning');
  else {
    validation.issues.forEach((issue) => {
      lines.push(`- [${issue.severity.toUpperCase()}] ${issue.code}: ${issue.message}`);
    });
  }

  lines.push('', '## ADK Adapter');
  if (analysis.blockers.length === 0) lines.push('- Blockers: none');
  else analysis.blockers.forEach((item) => lines.push(`- BLOCKED: ${item}`));
  analysis.warnings.forEach((item) => lines.push(`- PARTIAL: ${item}`));

  lines.push(
    '',
    '## Generation policy',
    '- Canvasにない業務ロジックは推測しない。',
    '- Routerの自然言語ConditionはPython条件式へ勝手に変換しない。',
    '- Toolの認証情報・Secretは生成コードへ埋め込まない。',
    '- LlmAgent/AgentはWorkflow Edge内で公開APIにより自動ラップされる前提。',
    '- HumanInputはRequestInput、JoinはJoinNodeへ変換する。',
    '- MCPはMcpToolset自体をLLM Agentへ付与できるが、決定論的なGraph Tool NodeとしてはTODOを残す。',
  );

  return lines.join('\n');
};

export const generateAdkProject = (
  project: GraphProject,
  settings: AdkAdapterSettings,
  validation: ValidationResult,
  analysis: AdkAdapterAnalysis,
): AdkCodeGeneration => {
  const symbols = makeSymbolMap(project);
  const agentPy = generateAgentPy(project, settings, symbols);
  const warnings = [...analysis.warnings];
  const requirements = 'google-adk>=2.0.0,<3.0.0\n';
  const mapping = generateMappingReport(
    project,
    settings,
    symbols,
    validation,
    analysis,
    agentPy.todos,
  );

  const files: AdkGeneratedFile[] = [
    { path: 'agent.py', language: 'python', content: agentPy.content },
    { path: 'requirements.txt', language: 'text', content: requirements },
    { path: 'mapping.md', language: 'markdown', content: mapping },
  ];

  return {
    files,
    todoCount: agentPy.todos.length,
    isRunnable:
      project.nodes.length > 0 &&
      validation.errors.length === 0 &&
      analysis.blockedCount === 0 &&
      agentPy.todos.length === 0,
    warnings,
  };
};
